(function(){var mzName="com_aquafadas_mz_v3";var mz=window[mzName];if(!mz){mz={};window[mzName]=mz;mz.log=false;mz.playerWrappers={};}
mz.bindFunction=function(scope,f){return function(){return f.apply(scope,arguments);};};mz.loadAndStartAnim=function(mzId,timeStamp,options){var l=new mz.Launcher();l.mzId=mzId;l.timeStamp=timeStamp;for(var key in options){if(l.hasOwnProperty(key)&&options[key]!==null){l[key]=options[key];}}
var wrapper=l.launch();mz.playerWrappers[mzId]=wrapper;return wrapper;};mz._triggerPlayerEvent=function(mzId,eventName){var playerWrapper=mz.playerWrappers[mzId];if(playerWrapper){playerWrapper._handleEvent(eventName);}};if(!mz.PlayerWrapper){mz.PlayerWrapper=function(mzId){this._id=mzId;this._created=false;this._started=false;this._playerObject=null;};mz.PlayerWrapper.prototype._setPlayerObject=function(playerObject){this._playerObject=playerObject;};mz.PlayerWrapper.prototype._handleEvent=function(eventName){switch(eventName){case"created":this._created=true;if(this.onCreated){this.onCreated(this);}
break;case"started":this._started=true;if(this.onStarted){this.onStarted(this);}
break;}};mz.PlayerWrapper.prototype._callOnPlayer=function(functionName,extraAttributes){if(this._started&&this._playerObject){var action={type:functionName};if(extraAttributes){for(var key in extraAttributes){action[key]=extraAttributes[key];}}
this._playerObject.publicActionCall(action);}};mz.PlayerWrapper.prototype.isCreated=function(){return this._created;};mz.PlayerWrapper.prototype.isStarted=function(){return this._started;};mz.PlayerWrapper.prototype.getId=function(){return this._id;};mz.PlayerWrapper.prototype.play=function(){this._callOnPlayer("play");};mz.PlayerWrapper.prototype.pause=function(){this._callOnPlayer("pause");};mz.PlayerWrapper.prototype.playPause=function(){this._callOnPlayer("playPause");};mz.PlayerWrapper.prototype.nextScene=function(playSlideTransition){this._callOnPlayer("nextScene",{playSlideTransition:playSlideTransition});};mz.PlayerWrapper.prototype.prevScene=function(){this._callOnPlayer("prevScene",{playSlideTransition:playSlideTransition});};mz.PlayerWrapper.prototype.nextSlide=function(playSlideTransition){this._callOnPlayer("nextSlide",{playSlideTransition:playSlideTransition});};mz.PlayerWrapper.prototype.prevSlide=function(){this._callOnPlayer("prevSlide",{playSlideTransition:playSlideTransition});};mz.PlayerWrapper.prototype.nextState=function(){this._callOnPlayer("nextState");};mz.PlayerWrapper.prototype.prevState=function(){this._callOnPlayer("prevState");};mz.PlayerWrapper.prototype.goTo=function(sceneIndex,slideIndex,stateIndex,pause,playSlideTransition){if(arguments.length==2||(arguments.length==3&&typeof arguments[2]=="boolean")){pause=stateIndex;stateIndex=slideIndex;slideIndex=sceneIndex;sceneIndex=0;playSlideTransition=false;}
this._callOnPlayer("goTo",{sceneIndex:sceneIndex,slideIndex:slideIndex,stateIndex:stateIndex,pause:pause,playSlideTransition:playSlideTransition});};}
if(!mz.Launcher){function getFolder(url){if(mz.log)console.log(url);var slashIndex=url.lastIndexOf("/");url=url.slice(0,slashIndex);return url;}
var scripts=document.getElementsByTagName("script");var srcPath=getFolder(scripts[scripts.length-1].src);var Launcher=function(){this.transparent=true;this.priorities=["flash","html5"];this.publishPath=null;this.isIOS=((navigator.userAgent.match(/iPhone/i))||(navigator.userAgent.match(/iPod/i))||(navigator.userAgent.match(/iPad/i)));this.hasCSSTransform=false;var prefixes='transform WebkitTransform MozTransform OTransform msTransform'.split(' '),elt=document.createElement('div');for(var i=0;i<prefixes.length;i++){if(elt.style[prefixes[i]]!=undefined){this.hasCSSTransform=true;break;}}
this.publishPath=getFolder(window.location.toString());this.mzId="mzDiv";if(mz.log)console.log("mzLauncher isIos: "+this.isIOS+" - hasCSSTransform: "+this.hasCSSTransform);};Launcher.prototype.launch=function(){this._playerWrapper=new mz.PlayerWrapper(this.mzId);if(document.getElementById(this.mzId)){this._onDOMReady();}else{if(document.addEventListener){document.addEventListener("DOMContentLoaded",mz.bindFunction(this,function(){document.removeEventListener("DOMContentLoaded",arguments.callee,false);this._onDOMReady();}),false);}else{document.attachEvent("onreadystatechange",mz.bindFunction(this,function(){document.detachEvent("DOMContentLoaded",arguments.callee);this._onDOMReady();}));}}
return this._playerWrapper;};Launcher.prototype.arrayIndexOf=function(array,object){for(var i=0,len=array.length;i<len;i++){if(array[i]==object){return i;}}
return-1;};Launcher.prototype._onDOMReady=function(){var that=this;this.mainDiv=document.getElementById(this.mzId);this.mainDiv.style.visibility="hidden";var html5Index=this.arrayIndexOf(this.priorities,"html5"),flashIndex=this.arrayIndexOf(this.priorities,"flash"),displayHTML5=this.hasCSSTransform&&html5Index>=0,displayFlash=flashIndex>=0,preferHTML5=false;if(displayHTML5){if(displayFlash){preferHTML5=html5Index<flashIndex;}else{preferHTML5=true;}}
var showAlternateContent=false;if(!displayHTML5&&!displayFlash){this.startAlternateContent();}else{if(!displayFlash||preferHTML5){this.startHTML5();}else{Launcher.loadScript(srcPath+"/flash/swfobject.js",this,function(){if(swfobject.hasFlashPlayerVersion("9.0.124")){if(mz.log)console.log("mzLauncher#launch - flash player detected");var swfLoadedCallBack=function(res){if(mz.log)console.log("swfLoadedCallBack",that.mzId,"res:",res.success);if(res.success){var flashObject=document.getElementById(res.id);that._playerWrapper._setPlayerObject(flashObject)}};params={};if(that.transparent)params.wmode="transparent";if(that.publishPath)params.publishPath=that.publishPath;swfobject.embedSWF(that.publishPath+"/mz.swf",that.mzId,"100%","100%","9.0.0",null,null,params,null,swfLoadedCallBack);}else{if(mz.log)console.log("mzLauncher#launch - flash player not available");if(displayHTML5){that.startHTML5();}else{that.startAlternateContent();}}},this.timeStamp);}}};Launcher.prototype.startAlternateContent=function(){this.mainDiv.style.visibility="visible";};Launcher.prototype.startHTML5=function(){var that=this;var loadAndStartJsDoc=function(){Launcher.loadScript(srcPath+'/'+lang+"/mzDoc.js",that,function(){that.mainDiv.style.visibility="visible";that.mainDiv.innerHTML="";var myDoc=mz.docs[that.mzId];var p=new mz.HTML5Player(myDoc,window,that.publishPath,that.timeStamp);that._playerWrapper._setPlayerObject(p)
p.init();},that.timeStamp);};if(!mz.Player){Launcher.loadScript(srcPath+"/html5/mz.js",this,loadAndStartJsDoc,this.timeStamp);}else{loadAndStartJsDoc();}};Launcher.loadScript=function(url,that,callback,timeStamp){var script=document.createElement("script");script.type="text/javascript";if(script.readyState){script.onreadystatechange=function(){if(script.readyState=="loaded"||script.readyState=="complete"){script.onreadystatechange=null;if(callback){callback.apply(that);}}};}else{script.onload=function(){if(mz.log)console.log("mzLauncher#script onload: "+url);if(callback){callback.apply(that);}};}
if(timeStamp)url+="#"+timeStamp;script.src=url;document.getElementsByTagName("head")[0].appendChild(script);if(mz.log)console.log("mzLauncher#startsLoadingScript: "+url)};mz.Launcher=Launcher;}})();
