(function(){var mzName="com_aquafadas_mz_v3";var mz=window[mzName];if(!mz){alert("launcher not loaded !");}
(function(){var lastTime=0;var vendors=['ms','moz','webkit','o'];for(var x=0;x<vendors.length&&!window.requestAnimationFrame;++x){window.requestAnimationFrame=window[vendors[x]+'RequestAnimationFrame'];window.cancelAnimationFrame=window[vendors[x]+'CancelAnimationFrame']||window[vendors[x]+'CancelRequestAnimationFrame'];}
var buggedOS=window.navigator.userAgent.indexOf("OS 6")>=0;if(!window.requestAnimationFrame||buggedOS){window.requestAnimationFrame=function(callback){var currTime=new Date().getTime();var timeToCall=Math.max(0,16-(currTime-lastTime));var id=window.setTimeout(function(){callback(currTime+timeToCall);},timeToCall);lastTime=currTime+timeToCall;return id;};}
if(!window.cancelAnimationFrame||buggedOS){window.cancelAnimationFrame=function(id){clearTimeout(id);};}}());mz.Timer={time:-1,get:function(){var val;if(this.time==-1){this.time=Date.now();val=0;}else{val=Date.now()-this.time;}
return"("+val+"ms)";}};mz.clone=function(obj,deep){var clone;if(mz.isArray(obj[key])){clone=[];}else{clone={};}
for(var key in obj){clone[key]=obj[key];if(deep&&typeof obj[key]==="object"){clone[key]=mz.clone(obj[key]);}}
return clone;};mz.isArray=function(val){return(Object.prototype.toString.call(val)==='[object Array]');};mz.CanvasUtils={drawRoundRect:function(ctx,w,h,r,doFill,doStroke,tl,tr,br,bl){r=Math.min(r,w/2,h/2);if(r==0){if(doFill)ctx.fillRect(0,0,w,h);if(doStroke)ctx.strokeRect(0,0,w,h);}else{var pi=Math.PI;var pi_2=Math.PI*0.5;var allCorners=arguments.length<=6;ctx.beginPath();if(allCorners||tl){ctx.moveTo(0,r);ctx.arc(r,r,r,-pi,-pi_2,false);}else{ctx.moveTo(0,0);}
if(allCorners||tr){ctx.lineTo(w-r,0);ctx.arc(w-r,r,r,-pi_2,0,false);}else{ctx.lineTo(w,0);}
if(allCorners||br){ctx.lineTo(w,h-r);ctx.arc(w-r,h-r,r,0,pi_2,false);}else{ctx.lineTo(w,h);}
if(allCorners||bl){ctx.lineTo(r,h);ctx.arc(r,h-r,r,pi_2,pi,false);}else{ctx.lineTo(0,h);}
if(allCorners||tl){ctx.lineTo(0,r);}else{ctx.lineTo(0,0);}
ctx.closePath();if(doFill)ctx.fill();if(doStroke)ctx.stroke();}}};mz.TextUtils={charTable:{"\n":"<br/>","\r":"<br/>","<":"&lt;",">":"&gt;","&":"&amp;"},toHTML:function(txt){var t="";for(var i=0;i<txt.length;i++){var c=txt[i];if(c in this.charTable){c=this.charTable[c];}
t+=c;}
return t;},splitGlyph:function(txt,div,dom){var elts=[];for(var i=0,len=txt.length;i<len;i++){var c=txt[i];var charElt;if(c=="\n"){charElt=dom.createElement("br");}else{if(c in mz.TextUtils.charTable){c=mz.TextUtils.charTable[c];}
charElt=dom.createElement("span");charElt.innerHTML=c;}
div.appendChild(charElt);elts.push(charElt);}
return elts;}};mz.Signal=function(){this._listeners=[];};mz.Signal.prototype.addListener=function(listener,thisObj){this._listeners.push([listener,thisObj]);};mz.Signal.prototype.dispatch=function(){for(var i=0,len=this._listeners.length;i<len;i++){var a=this._listeners[i];a[0].apply(a[1],arguments);}};if(!mz.Easing){mz.Easing={easeinquad:function(t,b,c,d){return c*(t/=d)*t+b;},easeoutquad:function(t,b,c,d){return-c*(t/=d)*(t-2)+b;},easeinoutquad:function(t,b,c,d){if((t/=d/2)<1)return c/2*t*t+b;return-c/2*((--t)*(t-2)-1)+b;},easeincubic:function(t,b,c,d){return c*(t/=d)*t*t+b;},easeoutcubic:function(t,b,c,d){return c*((t=t/d-1)*t*t+1)+b;},easeinoutcubic:function(t,b,c,d){if((t/=d/2)<1)return c/2*t*t*t+b;return c/2*((t-=2)*t*t+2)+b;},easeinquart:function(t,b,c,d){return c*(t/=d)*t*t*t+b;},easeoutquart:function(t,b,c,d){return-c*((t=t/d-1)*t*t*t-1)+b;},easeinoutquart:function(t,b,c,d){if((t/=d/2)<1)return c/2*t*t*t*t+b;return-c/2*((t-=2)*t*t*t-2)+b;},easeinquint:function(t,b,c,d){return c*(t/=d)*t*t*t*t+b;},easeoutquint:function(t,b,c,d){return c*((t=t/d-1)*t*t*t*t+1)+b;},easeinoutquint:function(t,b,c,d){if((t/=d/2)<1)return c/2*t*t*t*t*t+b;return c/2*((t-=2)*t*t*t*t+2)+b;},easeinsine:function(t,b,c,d){return-c*Math.cos(t/d*(Math.PI/2))+c+b;},easeoutsine:function(t,b,c,d){return c*Math.sin(t/d*(Math.PI/2))+b;},easeinoutsine:function(t,b,c,d){return-c/2*(Math.cos(Math.PI*t/d)-1)+b;},easeinexpo:function(t,b,c,d){return(t==0)?b:c*Math.pow(2,10*(t/d-1))+b;},easeoutexpo:function(t,b,c,d){return(t==d)?b+c:c*(-Math.pow(2,-10*t/d)+1)+b;},easeinoutexpo:function(t,b,c,d){if(t==0)return b;if(t==d)return b+c;if((t/=d/2)<1)return c/2*Math.pow(2,10*(t-1))+b;return c/2*(-Math.pow(2,-10*--t)+2)+b;},easeincirc:function(t,b,c,d){return-c*(Math.sqrt(1-(t/=d)*t)-1)+b;},easeoutcirc:function(t,b,c,d){return c*Math.sqrt(1-(t=t/d-1)*t)+b;},easeinoutcirc:function(t,b,c,d){if((t/=d/2)<1)return-c/2*(Math.sqrt(1-t*t)-1)+b;return c/2*(Math.sqrt(1-(t-=2)*t)+1)+b;},easeinelastic:function(t,b,c,d){var s=1.70158;var p=0;var a=c;if(t==0)return b;if((t/=d)==1)return b+c;if(!p)p=d*.3;if(a<Math.abs(c)){a=c;var s=p/4;}
else var s=p/(2*Math.PI)*Math.asin(c/a);return-(a*Math.pow(2,10*(t-=1))*Math.sin((t*d-s)*(2*Math.PI)/p))+b;},easeoutelastic:function(t,b,c,d){var s=1.70158;var p=0;var a=c;if(t==0)return b;if((t/=d)==1)return b+c;if(!p)p=d*.3;if(a<Math.abs(c)){a=c;var s=p/4;}
else var s=p/(2*Math.PI)*Math.asin(c/a);return a*Math.pow(2,-10*t)*Math.sin((t*d-s)*(2*Math.PI)/p)+c+b;},easeinoutelastic:function(t,b,c,d){var s=1.70158;var p=0;var a=c;if(t==0)return b;if((t/=d/2)==2)return b+c;if(!p)p=d*(.3*1.5);if(a<Math.abs(c)){a=c;var s=p/4;}
else var s=p/(2*Math.PI)*Math.asin(c/a);if(t<1)return-.5*(a*Math.pow(2,10*(t-=1))*Math.sin((t*d-s)*(2*Math.PI)/p))+b;return a*Math.pow(2,-10*(t-=1))*Math.sin((t*d-s)*(2*Math.PI)/p)*.5+c+b;},easeinback:function(t,b,c,d,s){if(s==undefined)s=1.70158;return c*(t/=d)*t*((s+1)*t-s)+b;},easeoutback:function(t,b,c,d,s){if(s==undefined)s=1.70158;return c*((t=t/d-1)*t*((s+1)*t+s)+1)+b;},easeinoutback:function(t,b,c,d,s){if(s==undefined)s=1.70158;if((t/=d/2)<1)return c/2*(t*t*(((s*=(1.525))+1)*t-s))+b;return c/2*((t-=2)*t*(((s*=(1.525))+1)*t+s)+2)+b;},easeinbounce:function(t,b,c,d){return c-mz.Easing.easeoutbounce(d-t,0,c,d)+b;},easeoutbounce:function(t,b,c,d){if((t/=d)<(1/2.75)){return c*(7.5625*t*t)+b;}else if(t<(2/2.75)){return c*(7.5625*(t-=(1.5/2.75))*t+.75)+b;}else if(t<(2.5/2.75)){return c*(7.5625*(t-=(2.25/2.75))*t+.9375)+b;}else{return c*(7.5625*(t-=(2.625/2.75))*t+.984375)+b;}},easeinoutbounce:function(t,b,c,d){if(t<d/2)return mz.Easing.easeinbounce(t*2,0,c,d)*.5+b;return mz.Easing.easeoutbounce(t*2-d,0,c,d)*.5+c*.5+b;},easeoutinquad:function(t,b,c,d,p_params){if(t<d/2)return mz.Easing.easeoutquad(t*2,b,c/2,d,p_params);return mz.Easing.easeinquad((t*2)-d,b+c/2,c/2,d,p_params);},easeoutincubic:function(t,b,c,d,p_params){if(t<d/2)return mz.Easing.easeoutcubic(t*2,b,c/2,d,p_params);return mz.Easing.easeincubic((t*2)-d,b+c/2,c/2,d,p_params);},easeoutinquart:function(t,b,c,d,p_params){if(t<d/2)return mz.Easing.easeoutquart(t*2,b,c/2,d,p_params);return mz.Easing.easeinquart((t*2)-d,b+c/2,c/2,d,p_params);},easeoutinquint:function(t,b,c,d,p_params){if(t<d/2)return mz.Easing.easeoutquint(t*2,b,c/2,d,p_params);return mz.Easing.easeinquint((t*2)-d,b+c/2,c/2,d,p_params);},easeoutinsine:function(t,b,c,d,p_params){if(t<d/2)return mz.Easing.easeoutsine(t*2,b,c/2,d,p_params);return mz.Easing.easeinsine((t*2)-d,b+c/2,c/2,d,p_params);},easeoutinexpo:function(t,b,c,d,p_params){if(t<d/2)return mz.Easing.easeoutexpo(t*2,b,c/2,d,p_params);return mz.Easing.easeinexpo((t*2)-d,b+c/2,c/2,d,p_params);},easeoutincirc:function(t,b,c,d,p_params){if(t<d/2)return mz.Easing.easeoutcirc(t*2,b,c/2,d,p_params);return mz.Easing.easeincirc((t*2)-d,b+c/2,c/2,d,p_params);},easeoutinelastic:function(t,b,c,d,p_params){if(t<d/2)return mz.Easing.easeoutelastic(t*2,b,c/2,d,p_params);return mz.Easing.easeinelastic((t*2)-d,b+c/2,c/2,d,p_params);},easeoutinback:function(t,b,c,d,p_params){if(t<d/2)return mz.Easing.easeoutback(t*2,b,c/2,d,p_params);return mz.Easing.easeinback((t*2)-d,b+c/2,c/2,d,p_params);},easeoutinbounce:function(t,b,c,d,p_params){if(t<d/2)return mz.Easing.easeoutbounce(t*2,b,c/2,d,p_params);return mz.Easing.easeinbounce((t*2)-d,b+c/2,c/2,d,p_params);}}}
if(!mz.TransitionEngine){mz.TransitionEngine=function(timeFactor){this._boundTic=mz.bindFunction(this,this._tic);this._boundEnd=mz.bindFunction(this,this._end);this._targetsMap={};this._transitions=[];if(timeFactor){this._timeFactor=timeFactor;}}
var p=mz.TransitionEngine.prototype;p._started=false;p._paused=false;p._rafId=false;p._transitions=null;p._targetsMap=null;p._duration=0;p._prevTime=0;p._progress=0;p._updateFunction=null;p._endFunction=null;p._boundTic=null;p._timeFactor=1;p.addTransition=function(t){if(this._started)this._error("0");if(!t||!t.target||!t.target.id||!t.target.properties)this._error("1");this._transitions.push(t);this._targetsMap[t.target.id]=t.target;};p.play=function(inDurationSec,updateFunction,endFunction){if(this._started)this._error("2");this._duration=inDurationSec*1000*this._timeFactor;this._updateFunction=updateFunction;this._endFunction=endFunction;this._started=true;this._prevTime=Date.now();this._progress=0;for(var i=0,len=this._transitions.length;i<len;i++){var t=this._transitions[i];if(t.d>0){if(t.hasOwnProperty("sv")){t.startValue=t.sv;}else{if(t.target.getValue){t.startValue=t.target.getValue(t.property);if(t.property=="r"){while(t.startValue<-180){t.startValue+=360;}
while(t.startValue>180){t.startValue-=360;}}}else{t.startValue=t.target.properties[t.property];}}}}
this._tic();};p.applyTransition=function(t){if(t.target.setValue){t.target.setValue(t.property,t.v);}else{t.target.properties[t.property]=t.v;}};p.pause=function(){if(!this._started||this._paused)this._error("3");this._paused=true;};p.resume=function(){if(!this._started||!this._paused)this._error("4")
this._prevTime=Date.now();this._paused=false;this._tic();};p.isStarted=function(){return this._started;};p.isPaused=function(){return this._paused;};p.stop=function(){if(!this._started)this._error("5");this._started=false;this._paused=false;this._transitions=[];this._targetsMap={};if(this._rafId){window.cancelAnimationFrame(this._rafId);}};p._error=function(eid){throw new Error("Tweener - error#"+eid);};p._tic=function(){if(this._paused||!this._started)return;var nowTime=Date.now();var p=this._progress+(nowTime-this._prevTime)/this._duration;if(p>1||this._duration==0){p=1;}
this._prevTime=nowTime;this._progress=p;for(var i=0,len=this._transitions.length;i<len;i++){var t=this._transitions[i];if(t){if(p>=t.de){var value;if(t.d==0||p>=t.d+t.de){value=t.v;this._transitions[i]=null;}else{var tweenProgress=(p-t.de)/t.d;if(t.e){var easingFunction=mz.Easing[t.e];if(easingFunction){tweenProgress=easingFunction(tweenProgress,0,1,1);}}
if(t.v instanceof Array){value=[];for(var iArray=0,lenArray=t.v.length;iArray<lenArray;iArray++){value[iArray]=~~(t.startValue[iArray]*(1-tweenProgress)+t.v[iArray]*tweenProgress);}}else{value=t.startValue*(1-tweenProgress)+t.v*tweenProgress;}}
if(t.target.setValue){t.target.setValue(t.property,value);}else{t.target.properties[t.property]=value;}
if(value===undefined){this._error("6");}}}}
for(var targetId in this._targetsMap){var target=this._targetsMap[targetId];if(target.update){target.update();}}
if(this._updateFunction){this._updateFunction(p);}
if(p==1){this._rafId=window.requestAnimationFrame(this._boundEnd);}else{this._rafId=window.requestAnimationFrame(this._boundTic);}};p._end=function(){this.stop();if(this._endFunction){this._endFunction();}};}
if(!mz.Effect){mz.Effect=function(){};var p=mz.Effect.prototype;p.init=function(doc,dom,player){this._doc=doc;this._dom=dom;this._player=player;};p.preprocessDocument=function(){for(var iSlide=0,lenSlide=this._player._allSlides.length;iSlide<lenSlide;iSlide++){var slide=this._player._allSlides[iSlide];for(var compId in slide.components){var component=slide.components[compId];if(component.hasEffect){for(var iState=0,lenState=slide.states.length;iState<lenState;iState++){var state=slide.states[iState];var transitions=state.transitions[component.id];var transitionWithEffect=null;for(var prop in transitions){var transition=transitions[prop];if(transition.effect&&(!transitionWithEffect||transition.de<transitionWithEffect.de)){transitionWithEffect=transition;}}
if(transitionWithEffect){if(component.type=="ImageComponent"){this.splitForImageEffect(transitionWithEffect);}else if(component.type=="VectorTextComponent"){this.splitForTextEffect(transitionWithEffect);}
this.prepareTransitionForEffect(transitionWithEffect,state);if(!component.effects){component.effects=[];}
component.effects[component.effects.length]=transitionWithEffect.effect;}}}}}};p.splitForImageEffect=function(transition){var effect=transition.effect;var comp=transition.target;effect.imgUrl=comp.imgSrc;var width=comp.settings.w;var height=comp.settings.h;var nCol=effect.col;var nRow=effect.row;if(width<nCol){nCol=width;}
if(height<nRow){nRow=height;}
var rw=Math.floor(width/nCol);var rh=Math.floor(height/nRow);var ew=width-nCol*rw;var eh=height-nRow*rh;var w=0;var h=0;var posX=0;var posY=0;var saveExtraWidth=ew;var elts=[];var cell;for(var i=0;i<nRow;i++){ew=saveExtraWidth;posX=0;h=rh;if(eh>0){eh--;h++;}
for(var j=0;j<nCol;j++){w=rw;if(ew>0){ew--;w++;}
elt={};elts.push(elt);elt.x=posX;elt.y=posY;elt.w=w;elt.h=h;posX+=w;}
posY+=h;}
effect.elts=elts;};p.splitForTextEffect=function(transition){var divElt=this._dom.createElement("div");this._doc.rootDivElt.appendChild(divElt);var startValues=transition.effect.startValues;divElt.style.width=startValues.w+"px";divElt.style.height=startValues.h+"px";divElt.style.fontSize=startValues.txtS+"px";divElt.style.fontFamily=startValues.txtF;divElt.style.textAlign=startValues.txtAl;var textComponent=transition.target;var spans=mz.TextUtils.splitGlyph(textComponent.txts[startValues.txt],divElt,this._dom);var elts=[];var s;var effect=transition.effect;if(effect.st=="glyph"){for(var i=0,len=spans.length;i<len;i++){s=spans[i];elts[i]={txt:s.innerHTML,x:s.offsetLeft,y:s.offsetTop,w:s.offsetWidth,h:s.offsetHeight};}}else{var cury=0;var curElt;var sp=false;var spW=0;for(var i=0;i<spans.length;i++){s=spans[i];var car=s.innerHTML;var y=s.offsetTop;if(effect.st=="word"){if(curElt&&y==cury&&car!=" "){curElt.txt+=car;}else{cury=y;if(car!=" "){curElt={txt:s.innerHTML,x:s.offsetLeft,y:s.offsetTop};elts[elts.length]=curElt;}else{curElt=null;}}}else{if(car==" "){if(curElt){sp=true;}}else{if(curElt&&y==cury){if(sp){curElt.txt+="&#160;"+car;}else{curElt.txt+=car;}}else{cury=y;curElt={txt:s.innerHTML,x:s.offsetLeft,y:s.offsetTop};elts[elts.length]=curElt;}
sp=false;}}}
if(spans.length>0){var span=spans[0];for(var i=0,len=elts.length;i<len;i++){var elt=elts[i];span.innerHTML=elt.txt;elt.w=span.offsetWidth;elt.h=span.offsetHeight;}}}
effect.elts=elts;if(elts.length>0){var baseTop=elts[0].y;for(i=0;i<elts.length;i++){elts[i].y-=baseTop;}}
this._doc.rootDivElt.removeChild(divElt);};p.prepareTransitionForEffect=function(transition){t=[{de:transition.de,d:0,v:transition.v,property:"v",target:transition.target}];if(transition.v==0){t[0].de+=transition.d;}
t[t.length]={de:transition.de,d:0,v:transition.effect,property:"_effect",target:transition.target};t[t.length]={de:transition.de+transition.d,d:0,v:null,property:"_effect",target:transition.target};var effect=transition.effect;for(var i=0,len=effect.elts.length;i<len;i++){var elt=effect.elts[i];elt.settings=mz.clone(this._player.defaultValues);elt.settings.ox=effect.ox;elt.settings.oy=effect.oy;elt.settings.x=elt.x+~~(effect.ox*elt.w);elt.settings.y=elt.y+~~(effect.oy*elt.h);elt.settings.w=elt.w;elt.settings.h=elt.h;elt.settings._floorOxy=true;this._player.extendForTransitionEngine(elt);elt.id=transition.target.id+"_effectElt_"+i;}
var eltDuR=(1-effect.t)*transition.d;var elts=effect.elts;if(effect.dir=="random"){elts=elts.concat();}else if(effect.dir=="left"){elts=elts.reverse();}
var appear=transition.v==true;for(var i=0,l=elts.length;i<l;i++){var elt;if(effect.dir=="random"){var idx=i+Math.round(Math.random()*(l-i-1));elt=elts[idx];elts[idx]=elts[i];elts[i]=elt;}else if(effect.dir=="center"){if((i%2)===0){elt=elts[i/2];}else{elt=elts[l-1-((i-1)/2)];}}else if(effect.dir=="edge"){var centerPos;if((l%2)===0){centerPos=l/2-1;}else{centerPos=Math.floor(l/2);}
if((i%2)===0){elt=elts[centerPos-i/2];}else{elt=elts[centerPos+1+((i-1)/2)];}}else{elt=elts[i];}
var eltDeR=effect.t*(i/l)*transition.d+transition.de;if(!effect.vis){if(appear){elt.settings.v=false;t[t.length]={de:eltDeR,d:0,property:"v",target:elt,sv:false,v:true};}else{elt.settings.v=true;t[t.length]={de:eltDeR+eltDuR,d:0,property:"v",target:elt,sv:true,v:false};}}
if(effect.tweens){for(var iTween=0;iTween<effect.tweens.length;iTween++){var tween=effect.tweens[iTween];var prop=tween.prop;var tweenVal=tween.val;if(prop=="x"||prop=="y"){var size;if(prop=="x"){size=effect.startValues.w;}else{size=effect.startValues.h;}
if(effect["a"+prop]){tweenVal=effect["a"+prop+"r"]*size;}else{if(effect["s"+prop]!=1){tweenVal+=effect["s"+prop]*(elt.settings[prop]-size*effect["o"+prop])+size*effect["o"+prop];}else{tweenVal+=elt.settings[prop];}}}
if(tween.rr){tweenVal+=tween.rr*2*(Math.random()-0.5);}
var tObj={de:eltDeR+tween.de*eltDuR,d:tween.d*eltDuR,e:tween.e,property:prop,target:elt};t[t.length]=tObj;var idleValue=elt.settings[prop];var newVal;if(appear){tObj.sv=tweenVal;tObj.v=idleValue;}else{tObj.sv=idleValue;tObj.v=tweenVal;}
elt.settings[prop]=tObj.sv;}}}
transition.effect.transitions=t;};}
if(!mz.DOMComponent){mz.DOMComponent=function(){};mz.DOMComponent._classMap={};(function(){var ua=navigator.userAgent;ua=ua.toLowerCase();var useBackfaceVisibility=true;if(ua.indexOf('applewebkit')>=0){if(ua.indexOf('safari')>=0){if(ua.indexOf('chrome')<0){var index=ua.indexOf("version/");if(index>=0){var safariVersion=parseFloat(ua.slice(index+8));if(safariVersion>=6.1){useBackfaceVisibility=false;}}}}else{if(ua.indexOf("mac os x 10_9")>=0){useBackfaceVisibility=false;}}}
if(useBackfaceVisibility){if(ua.indexOf("ipad")>0||ua.indexOf("iphone")>0||ua.indexOf("ipod")>0){index=ua.indexOf("os ");var iosVersion=parseFloat(ua.slice(index+3));if(iosVersion>=7){useBackfaceVisibility=false;}}}
mz.DOMComponent.useBackfaceVisibility=useBackfaceVisibility;})();mz.DOMComponent.prototype.build=function(player){this.flags={};this.player=player;this.rootDivElt=this.createDiv("0px","0px");this.rootDivElt.id=this.id;this.divElt=this.createDiv();this.rootDivElt.appendChild(this.divElt);if(!this.hasEffect&&!this.hasMask){this.contentElt=this.divElt;}else{this.contentElt=this.createDiv("100%","100%");this.divElt.appendChild(this.contentElt);}
var self=this;var clickHandler=function(){var action=false;if(self.properties.oc){if(mz.log)console.log("Click Action");player.executeAction(self.properties.oc);action=true;}
if(self.afterClick){self.afterClick();action=true;}
return!action;};if(!!('ontouchstart'in window)){this.rootDivElt.ontouchstart=clickHandler;}else{this.rootDivElt.onclick=clickHandler;}
if(this._extend_build){this._extend_build();if(this.hasEffect&&this.effects){for(var i=0,len=this.effects.length;i<len;i++){var effect=this.effects[i];effect.divElt=this.createDiv("100%","100%");this.divElt.appendChild(effect.divElt);effect.divElt.style.display="none";for(var j=0,len2=effect.elts.length;j<len2;j++){var elt=effect.elts[j];elt.rootDivElt=this.createDiv("0px","0px");elt.rootDivElt.id=elt.id;elt.divElt=this.createDiv(elt.w+"px",elt.h+"px");elt.rootDivElt.appendChild(elt.divElt);effect.divElt.appendChild(elt.rootDivElt);this._extend_buildEffectElt(elt,effect);elt.flags={};elt.update=this.update;elt.getValue=this.getValue;elt.setValue=this.setValue;elt.propertyMap=this.propertyMap;}}}}
return this.rootDivElt;};mz.DOMComponent.prototype.createDiv=function(w,h){var divElt=this._dom.createElement("div");divElt.style.position="absolute";if(w)divElt.style.width=w;if(h)divElt.style.height=h;if(mz.DOMComponent.useBackfaceVisibility){divElt.style.webkitBackfaceVisibility="hidden";}
return divElt;};mz.DOMComponent.prototype.update=function(force){var style;var p=this.properties;if(this.hasMask&&(force||this.flags.hasOwnProperty("mask"))){if(this.properties.m=="rel"){this.divElt.style.overflow="hidden";this.contentElt.style.width="100%";this.contentElt.style.height="100%";mz.DOMRenderer.setCSSTransform("",this.contentElt);}else{this.divElt.style.overflow="visible";}}
if(p.m!="rel"){if(force||this.flags.hasOwnProperty("size")){this.divElt.style.width=p.w+"px";this.divElt.style.height=p.h+"px";}
if(force||this.flags.hasOwnProperty("origin")||this.flags.hasOwnProperty("size")){if(!this.settings._floorOxy){style="translate("+(-p.w*p.ox)+"px,"+(-p.h*p.oy)+"px)";}else{style="translate("+(~~(-p.w*p.ox))+"px,"+(~~(-p.h*p.oy))+"px)";}
mz.DOMRenderer.setCSSTransform(style,this.divElt);}}else{if(force||this.flags.hasOwnProperty("mask")||this.flags.hasOwnProperty("size")){this.divElt.style.width=p.mw+"px";this.divElt.style.height=p.mh+"px";this.contentElt.style.width=p.w+"px";this.contentElt.style.height=p.h+"px";}
if(force||this.flags.hasOwnProperty("origin")||this.flags.hasOwnProperty("size")||this.flags.hasOwnProperty("mask")){var contentX=(-p.w*p.ox);var contentY=(-p.h*p.oy);style="translate("+(contentX+p.mx)+"px,"+(contentY+p.my)+"px)";mz.DOMRenderer.setCSSTransform(style,this.divElt);style="translate("+(-p.mx)+"px,"+(-p.my)+"px)";mz.DOMRenderer.setCSSTransform(style,this.contentElt);}}
if(force||this.flags.hasOwnProperty("transform")){style="translate("+p.x+"px,"+p.y+"px) ";if(p.r){style+="rotate("+p.r+"deg)";}
if(p.sx!=1||p.sy!=1){style+="scale("+p.sx+","+p.sy+") "}
mz.DOMRenderer.setCSSTransform(style,this.rootDivElt);}
if(force||this.flags.hasOwnProperty("v")){if(this.properties.v){this.divElt.style.visibility="visible";}else{this.divElt.style.visibility="hidden";}}
if(force||this.flags.hasOwnProperty("a")){this.divElt.style.opacity=this.properties.a;}
if(force||this.flags.hasOwnProperty("btn")){if(this.properties.btn){this.divElt.style.cursor="pointer";}else{this.divElt.style.cursor="auto";}}
if(this.effects&&(force||this.flags.hasOwnProperty("_effect"))){if(this.properties._effect){this.contentElt.style.display="none";this.properties._effect.divElt.style.display="block";this.effects.displayedEffect=this.properties._effect;}else{if(this.effects.displayedEffect){this.contentElt.style.display="block";this.effects.displayedEffect.divElt.style.display="none";this.effects.displayedEffect=null;}}}
if(this.slide&&(force||this.flags.hasOwnProperty("_parent"))){if(!this.properties._parent){if(this.rootDivElt.parentNode!=this.slide.divElt){this.slide.divElt.appendChild(this.rootDivElt);}}else{if(this.rootDivElt.parentNode!=this.properties._parent.contentElt){this.properties._parent.contentElt.appendChild(this.rootDivElt);}}}
if(this._extend_update){this._extend_update(force);}
for(var prop in this.flags){delete this.flags[prop];}};mz.DOMComponent.prototype.getValue=function(prop){return this.properties[prop];};mz.DOMComponent.prototype.setValue=function(prop,value){this.properties[prop]=value;var propFlag=this.propertyMap[prop];if(!propFlag&&this._extend_propertyMap){propFlag=this._extend_propertyMap[prop];}
if(propFlag){this.flags[propFlag]=true;}else{this.flags[prop]=true;}};mz.DOMComponent.prototype.propertyMap={_parent:null,oc:"action",x:"transform",y:"transform",w:"size",h:"size",ox:"origin",oy:"origin",sx:"transform",sy:"transform",r:"transform",v:null,a:null,m:"mask",mx:"mask",my:"mask",mw:"mask",mh:"mask",btn:null};var Img=mz.DOMComponent._classMap.ImageComponent=function(){};Img.prototype._extend_propertyMap={};Img.prototype._extend_build=function(){};Img.prototype._extend_update=function(force){if(force){var css;if(this.settings.src){css="url('"+this.settings.src+"')";}else{css="";}
if(this.contentElt.style.backgroundImage!=css){this.contentElt.style.backgroundImage=css;}}};Img.prototype._extend_buildEffectElt=function(elt,effect){elt.divElt.style.backgroundImage="url("+effect.imgUrl+")";elt.divElt.style.backgroundPosition=(-elt.x)+"px "+(-elt.y)+"px";};var Rectangle=mz.DOMComponent._classMap.RectangleShapeComponent=function(){};Rectangle.prototype._extend_propertyMap={bw:"border",bc:"border",ba:"border",btl:"border",btr:"border",bbl:"border",bbr:"border",br:"border",gc0:"gradient",gc1:"gradient",gc2:"gradient",gc3:"gradient",gc4:"gradient",ga0:"gradient",ga1:"gradient",ga2:"gradient",ga3:"gradient",ga4:"gradient",gr0:"gradient",gr1:"gradient",gr2:"gradient",gr3:"gradient",gr4:"gradient",gnc:"gradient",gr:"gradient",gx1:"gradient",gy1:"gradient",gx2:"gradient",gy2:"gradient",gra:"gradient"};Rectangle.prototype._extend_build=function(){};Rectangle.prototype._extend_update=function(force){if(force||this.flags.hasOwnProperty("gradient")||(this.contentElt._gradientElt&&this.flags.size&&this.contentElt._gradientElt.style.visibility=="visible")||(this.contentElt._gradientElt&&this.flags.border)){this._renderer._drawGradient(this.contentElt,this.properties);}
if(force||this.flags.hasOwnProperty("border")){this._renderer._drawBorder(this.contentElt,this.properties);}};var Txt=mz.DOMComponent._classMap.VectorTextComponent=function(){};Txt.prototype._extend_propertyMap={txt:null,txtS:null,txtC:null,txtF:null,txtAl:null};Txt.prototype._extend_build=function(){this.contentElt.style.overflow="hidden";if(this.hasEffect){this._txtDivs=[];for(var i=0,len=this.txts.length;i<len;i++){var div=this._dom.createElement("div");div.style.position="absolute";div.style.width="100%";div.style.height="100%";div.style.display="none";mz.TextUtils.splitGlyph(this.txts[i],div,this._dom);this._txtDivs[i]=div;this.contentElt.appendChild(div);}
this._displayTextDiv(0);}};Txt.prototype._extend_update=function(){if(this.flags.hasOwnProperty("txt")){if(this.hasEffect){this._displayTextDiv(this.properties.txt);}else{this.contentElt.innerHTML=mz.TextUtils.toHTML(this.txts[this.properties.txt]);}}
if(this.flags.hasOwnProperty("txtS")){this.divElt.style.fontSize=this.properties.txtS+"px";}
if(this.flags.hasOwnProperty("txtC")){this.divElt.style.color="rgb("+this.properties.txtC+")";}
if(this.flags.hasOwnProperty("txtF")){this.divElt.style.fontFamily=this.properties.txtF;}
if(this.flags.hasOwnProperty("txtF")){this.divElt.style.textAlign=this.properties.txtAl;}};Txt.prototype._displayTextDiv=function(index){if(this._currentTextDiv){this._currentTextDiv.style.display="none";}
this._currentTextDiv=this._txtDivs[index];this._currentTextDiv.style.display="block";};Txt.prototype._extend_buildEffectElt=function(elt,effect){elt.divElt.innerHTML=elt.txt;};var HtmlText=mz.DOMComponent._classMap.HtmlTextComponent=function(){};HtmlText.prototype._extend_propertyMap={txt:null};HtmlText.prototype._extend_build=function(){this.contentElt.style.overflow="hidden";};HtmlText.prototype._extend_update=function(){if(this.flags.hasOwnProperty("txt")){this.contentElt.innerHTML=this.properties.txt;}};mz.DOMComponent._classMap.RichTextComponent=HtmlText;var Group=mz.DOMComponent._classMap.ComponentGroup=function(){};Group.prototype._extend_propertyMap={};Group.prototype._extend_build=function(){};Group.prototype._extend_update=function(){};function extendRectangle(comp){comp.prototype._extend_propertyMap=mz.clone(Rectangle.prototype._extend_propertyMap);comp.prototype._extend_propertyMap.fill="sound";if(comp==Volume){comp.prototype._extend_propertyMap.empty="sound";}
var buildF=comp.prototype._extend_build;comp.prototype._extend_build=function(){this.canvas=document.createElement("canvas");this.canvas.style.position="absolute";this.canvas.style.left="0px";this.canvas.style.right="0px";this.contentElt.appendChild(this.canvas);if(this.player._soundManager){this._soundManager=this.player._soundManager;}
Rectangle.prototype._extend_build.call(this);buildF.call(this);};var updateF=comp.prototype._extend_update;comp.prototype._extend_update=function(force){Rectangle.prototype._extend_update.call(this,force);updateF.call(this,force);}}
var Mute=mz.DOMComponent._classMap.MuteSoundComponent=function(){};Mute.prototype._extend_build=function(){if(this._soundManager){this._soundManager.onVolumeChange.addListener(this.redrawIcon,this);}};Mute.prototype._extend_update=function(force){if(force||this.flags.size||this.flags.sound){this.redrawIcon();}};Mute.prototype.afterClick=function(){if(this._soundManager){this._soundManager.setMute(!this._soundManager.getMute());}};Mute.prototype.redrawIcon=function(){var w=this.properties.w;var h=this.properties.h;var size=(w<h)?w:h;var c=this.canvas;c.width=size;c.height=size;c.style.left=~~((w-size)/2)+"px";c.style.top=~~((h-size)/2)+"px";var ctx=c.getContext("2d");ctx.fillStyle="rgb("+this.properties.fill+")";ctx.beginPath();ctx.moveTo(0.15*size,0.4*size);ctx.lineTo(0.25*size,0.4*size);ctx.lineTo(0.5*size,0.15*size);ctx.lineTo(0.5*size,0.85*size);ctx.lineTo(0.25*size,0.6*size);ctx.lineTo(0.15*size,0.6*size);ctx.fill();if(this._soundManager&&!this._soundManager.getMute()){var cone=0.25*Math.PI,cx=0.36*size;ctx.strokeStyle="rgb("+this.properties.fill+")";ctx.lineWidth=size*0.05;ctx.beginPath();ctx.arc(cx,size*0.5,size*0.3,cone,-cone,true);ctx.stroke();ctx.beginPath();ctx.arc(cx,size*0.5,size*0.4,cone,-cone,true);ctx.stroke();ctx.beginPath();ctx.arc(cx,size*0.5,size*0.5,cone,-cone,true);ctx.stroke();}};extendRectangle(Mute);var Volume=mz.DOMComponent._classMap.VolumeSoundComponent=function(){};Volume.prototype._extend_build=function(){if(this._soundManager){this._soundManager.onVolumeChange.addListener(this.redrawIcon,this);}
var self=this;this.canvas.onmousedown=function(e){self.volumeMouseDown(e);}};Volume.prototype._extend_update=function(force){if(force||this.flags.size||this.flags.sound){this.redrawIcon();}};Volume.prototype.redrawIcon=function(){var w=this.properties.w;var h=this.properties.h;var c=this.canvas;c.width=w;c.height=h;var ctx=c.getContext("2d");ctx.fillStyle="rgb("+this.properties.empty+")";ctx.beginPath();ctx.moveTo(0.1*w,0.9*h);ctx.lineTo(0.9*w,0.1*h);ctx.lineTo(0.9*w,0.9*h);ctx.fill();if(this._soundManager){var volume=this._soundManager.getGlobalVolume()/100;if(volume>0){ctx.fillStyle="rgb("+this.properties.fill+")";ctx.beginPath();ctx.moveTo(0.1*w,0.9*h);ctx.lineTo((0.1+0.8*volume)*w,0.9*h);ctx.lineTo((0.1+0.8*volume)*w,(0.9-0.8*volume)*h);ctx.fill();}}};Volume.prototype.volumeMouseDown=function(e){var target=document;if(!this._onMove){var self=this;this._onMove=function(e){self.updateVolumeWithMousePos(e);};this._onUp=function(e){if(e.type=="mouseup"){target.removeEventListener("mousemove",self._onMove,false);target.removeEventListener("mouseup",self._onUp,false);}};}
target.addEventListener("mousemove",this._onMove);target.addEventListener("mouseup",this._onUp);this.updateVolumeWithMousePos(e);};Volume.prototype.updateVolumeWithMousePos=function(e){var posX=e.hasOwnProperty('offsetX')?e.offsetX:e.layerX;var vol=100*(posX-0.1*this.canvas.width)/(0.8*this.canvas.width);if(vol<0){vol=0;}else if(vol>100){vol=100;}
if(this._soundManager){this._soundManager.setGlobalVolume(vol);}};extendRectangle(Volume);var ToggleSound=mz.DOMComponent._classMap.ToggleSoundComponent=function(){};ToggleSound.prototype._extend_build=function(){if(this._soundManager){this._soundManager.onSoundChange.addListener(this.onSoundChange,this);}};ToggleSound.prototype.onSoundChange=function(soundId){if(soundId==this._soundId){this.redrawIcon();}};ToggleSound.prototype._extend_update=function(force){if(force||this.flags.action){var newSoundId=null;var actions=this.properties.oc;if(actions&&actions.length){for(var i=0,len=actions.length;i<len;i++){var a=actions[i];if(a&&a.type=="sound"&&a.operation=="togglePlay"){newSoundId=a.soundId;break;}}}
if(newSoundId!=this._soundId){this._soundId=newSoundId;force=true;}}
if(force||this.flags.size||this.flags.sound){this.redrawIcon();}};ToggleSound.prototype.redrawIcon=function(){var w=this.properties.w;var h=this.properties.h;var size=(w<h)?w:h;var c=this.canvas;c.width=size;c.height=size;c.style.left=~~((w-size)/2)+"px";c.style.top=~~((h-size)/2)+"px";var ctx=c.getContext("2d");ctx.fillStyle="rgb("+this.properties.fill+")";if(this._soundId){if(!this._soundManager.isSoundPlaying(this._soundId)){ctx.beginPath();ctx.moveTo(0.35*size,0.2*size);ctx.lineTo(0.85*size,0.5*size);ctx.lineTo(0.35*size,0.8*size);ctx.fill();}else{ctx.fillRect(0.25*size,0.25*size,0.2*size,0.5*size);ctx.fillRect(0.55*size,0.25*size,0.2*size,0.5*size);}}};extendRectangle(ToggleSound);mz.DOMComponent.extendModel=function(component,renderer){component._renderer=renderer;component._dom=renderer._dom;for(var prop in mz.DOMComponent.prototype){component[prop]=mz.DOMComponent.prototype[prop];}
var classObj=mz.DOMComponent._classMap[component.type];for(var prop in classObj.prototype){component[prop]=classObj.prototype[prop];}};}
if(!mz.DOMRenderer){mz.DOMRenderer=function(doc,win,player){if(mz.log)console.log("DOMRenderer#constructor",doc,win);this._doc=doc;this._win=win;this._dom=win.document;this._rootDivElt=null;this._nextSlide=null;this._player=player;};var p=mz.DOMRenderer.prototype;mz.DOMRenderer.slideUpdateFunction=function(){var p=this.properties;this.divElt.style.opacity=p.a;mz.DOMRenderer.setCSSTransform("translate("+p.x+"px , "+p.y+"px)",this.divElt);};p.initRootDiv=function(rootDiv){if(mz.log)console.log("DOMRenderer#initRootDiv",rootDiv)
this._rootDivElt=rootDiv;var s=rootDiv.style;s.backgroundColor="rgba("+this._doc.bgc+")";s.width=this._doc.w+"px";s.height=this._doc.h+"px";s.webkitFontSmoothing="antialiased";s.overflow="hidden";s.position="absolute";s.webkitTapHighlightColor="antialiased";s.WebkitTouchCallout="none";s.WebkitUserSelect="none";s.KhtmlUserSelect="none";s.MozUserSelect="none";s.msUserSelect="none";s.userSelect="none";};p.prepareDomSlide=function(slide){slide.update=mz.DOMRenderer.slideUpdateFunction;var div=slide.divElt;div.id=this._doc.mzId+"_"+slide.id;if(slide.g){this._drawGradient(slide.divElt,slide.g);this._drawBorder(slide.divElt,slide.g);}
div.style.position="absolute";div.style.width=this._doc.w+"px";div.style.height=this._doc.h+"px";div.style.overflow="hidden";div.style.left="0px";div.style.top="0px";this._rootDivElt.appendChild(div);};p.prepareAnimation=function(){if(mz.log)console.log("DOMRenderer#prepareAnimation");var div,slides=this._player._allSlides;for(var iSlide=0,lenSlide=slides.length;iSlide<lenSlide;iSlide++){var slide=slides[iSlide];slide.divElt=this._dom.createElement("div");this.prepareDomSlide(slide);this.hideSlide(slide);for(var componentId in slide.components){var component=slide.components[componentId];mz.DOMComponent.extendModel(component,this);slide.divElt.appendChild(component.build(this._player));}}};p.initSlide=function(slide){this.initState(slide.states[0],slide);if(mz.slidePolicy!=null){var slides=this._player._allSlides;var slideIndex=slides.indexOf(slide),nextSlideIndex=-1,prevSlideIndex=-1;if(mz.slidePolicy.next){nextSlideIndex=slideIndex+1;if(nextSlideIndex>=slides.length){if(mz.slidePolicy.loop){nextSlideIndex=0;}else{nextSlideIndex=-1;}}}
if(mz.slidePolicy.prev){prevSlideIndex=slideIndex-1;if(prevSlideIndex<0){if(mz.slidePolicy.loop){prevSlideIndex=slides.length-1;}else{prevSlideIndex=-1;}}}
for(var i=0;i<this._doc.slides.length;i++){var iSlide=this._doc.slides[i];if(iSlide==slide||i==nextSlideIndex||i==prevSlideIndex){iSlide.divElt.style.display="block";}else{iSlide.divElt.style.display="none";}}}};p.showSlide=function(slide){if(mz.log)console.log("@@@@@@@@@@@@@@@@@@@DOMRenderer#showSlide",slide);slide.divElt.style.zIndex=1;slide.divElt.style.top="0px";};p.hideSlide=function(slide){if(mz.log)console.log("@@@@@@@@@@@@@@@@@@@DOMRenderer#hideSlide",slide);slide.divElt.style.zIndex=0;slide.divElt.style.top=this._doc.h+"px";};p.prepareForSlideTransition=function(inSlide,outSlide){if(outSlide){this.showSlide(outSlide);}
if(inSlide){this.showSlide(inSlide);inSlide.divElt.style.zIndex=2;}};p.takeSlideSnapShot=function(slide){var fakeSlide={};fakeSlide.id="fakeSlide";var snapShotDiv=slide.divElt.cloneNode(true);fakeSlide.divElt=snapShotDiv;this.prepareDomSlide(fakeSlide);this._rootDivElt.appendChild(snapShotDiv);this.showSlide(fakeSlide);return fakeSlide;};p.disposeSlideSnapShot=function(slide){this._rootDivElt.removeChild(slide.divElt);};p.initState=function(state,slide){if(state.sortedDisplayList){for(var i=0,lenI=state.sortedDisplayList.length;i<lenI;i++){var componentId=state.sortedDisplayList[i];var component=slide.components[componentId];component.rootDivElt.style.zIndex=i;}}
slide.update();for(var componentId in slide.components){var component=slide.components[componentId];component.update();}};p.update=function(progress){};p.slideTransitionUpdate=function(progress){};p._drawGradient=function(div,g){if(!g._gradientChecked){g._gradientChecked=true;for(var i=0;i<5;i++){if(!g.hasOwnProperty("ga"+i)){g["ga"+i]=1;}}
if(!g.gr0){g.gr0=0;}}
if(g.gnc===0){div.style.background="none";if(div._gradientElt){div._gradientElt.style.visibility="hidden";}}else if(g.gnc==1){div.style.background="rgba("+g.gc0+" , "+g.ga0+")";if(div._gradientElt){div._gradientElt.style.visibility="hidden";}}else{if(g.gc0){if(g.hasOwnProperty("ga0")){div.style.backgroundColor="rgba("+g.gc0+","+g.ga0+")";}}
if(navigator.userAgent.indexOf("WebKit")>-1){var css="";if(g.gr){css="-webkit-gradient( radial , "+g.gx1*100+"% "+g.gy1*100+"%, 0 , "+g.gx1*100+"% "+g.gy1*100+"%, "+g.gra+" ";}else{css="-webkit-gradient( linear , "+g.gx1*100+"% "+g.gy1*100+"%, "+g.gx2*100+"% "+g.gy2*100+"% ";}
for(var i=0;i<g.gnc;i++){css+=", color-stop("+g["gr"+i]+" , rgba("+g["gc"+i]+","+g["ga"+i]+"))";}
css+=")";div.style.background=css;}else{if(!div._gradientElt){div._gradientElt=this._dom.createElement('canvas');div._gradientElt.style.zIndex=-2;div._gradientElt.style.position="absolute";div.appendChild(div._gradientElt);}
div._gradientElt.style.visibility="visible";var ctx=div._gradientElt.getContext('2d');div._gradientElt.width=parseInt(div.style.width);div._gradientElt.height=parseInt(div.style.height);var grad;if(g.gr){grad=ctx.createRadialGradient(g.gx1,g.gy1,0,g.gx1,g.gy1,g.gra);}else{grad=ctx.createLinearGradient(g.gx1*div._gradientElt.width,g.gy1*div._gradientElt.height,g.gx2*div._gradientElt.width,g.gy2*div._gradientElt.height);}
for(var i=0;i<g.gnc;i++){grad.addColorStop(g["gr"+i],"rgba("+g["gc"+i]+","+g["ga"+i]+")");}
ctx.fillStyle=grad;var w=div._gradientElt.width,h=div._gradientElt.height,b=g;if(b.br>0&&(b.btl||b.bbl||b.btr||b.bbr)){var r=b.br;mz.CanvasUtils.drawRoundRect(ctx,w,h,r,true,false,b.btl,b.btr,b.bbr,b.bbl);}else{ctx.fillRect(0,0,w,h);}}}};p._drawBorder=function(div,b){if(!b._borderChecked){b._borderChecked=true;var defaultProperties={bw:0,ba:1,btl:0,btr:0,bbl:0,bbr:0,br:0};for(var prop in defaultProperties){if(!b.hasOwnProperty(prop)){b[prop]=defaultProperties[prop];}}}
if(!div._borderElt){div._borderElt=this._dom.createElement("div");div._borderElt.style.position="absolute";div._borderElt.style.zIndex=-1;div.appendChild(div._borderElt);}else{div._borderElt.style.display="block";}
div._borderElt.style.border=b.bw+"px solid rgba("+b.bc+","+b.ba+")";div._borderElt.style.left=-(b.bw*0.5)+"px";div._borderElt.style.right=-(b.bw*0.5)+"px";div._borderElt.style.top=-(b.bw*0.5)+"px";div._borderElt.style.bottom=-(b.bw*0.5)+"px";for(var i=0;i<2;i++){var s=(i==0)?div.style:div._borderElt.style;s.borderTopLeftRadius=b.btl*b.br+"px";s.borderBottomLeftRadius=b.bbl*b.br+"px";s.borderTopRightRadius=b.btr*b.br+"px";s.borderBottomRightRadius=b.bbr*b.br+"px";}};(function(){var prefixes='transform WebkitTransform MozTransform OTransform msTransform'.split(' '),elt=document.createElement('div');for(var i=0;i<prefixes.length;i++){if(elt.style[prefixes[i]]!=undefined){mz.DOMRenderer._transformCSSName=prefixes[i];break;}}})();mz.DOMRenderer.setCSSTransform=function(style,divElt){divElt.style[mz.DOMRenderer._transformCSSName]=style;};}
if(!mz.Preloader){mz.Preloader=function(doc,win){if(mz.log)console.log("DOMRenderer#constructor",doc,win);this._doc=doc;this._win=win;this._dom=win.document;this._canvasElt=null;this.divElt=null;this._boundUpdate=mz.bindFunction(this,this._update);doc.preloader.d*=1000;this.id=doc.mzId+"_Preloader";};var p=mz.Preloader.prototype;p.displayInRootDiv=function(rootDiv){if(mz.log)console.log("Preloader#displayInRootDiv",rootDiv)
this._rootDivElt=rootDiv;var p=this._doc.preloader;var c=this._canvasElt=this._dom.createElement("canvas");c.id="mzPreloader";c.style.zIndex=1000;c.style.position="absolute";c.style.left=~~((this._doc.w-p.sqr.s)*0.5)+"px";c.style.top=~~((this._doc.h-p.sqr.s)*0.5)+"px";c.width=p.sqr.s;c.height=p.sqr.s;this._time=0;this._prevTime=new Date().getTime();this.divElt=this._dom.createElement("div");this.divElt.style.position="absolute";this.divElt.style.left="0px";this.divElt.style.top="0px";this.divElt.appendChild(this._canvasElt);this._rootDivElt.appendChild(this.divElt);this.divElt.id=this.id;window.requestAnimationFrame(this._boundUpdate);this._displayed=true;};p._update=function(){if(this._canvasElt&&this._displayed){var c=this._canvasElt,ctx=c.getContext('2d'),p=this._doc.preloader;var newTime=new Date().getTime();this._time+=(newTime-this._prevTime)
this._prevTime=newTime;if(this._time>p.d){this._time-=p.d;}
var progress=this._time/p.d
c.width=c.width;ctx.fillStyle="rgba("+p.sqr.bgc+")";mz.CanvasUtils.drawRoundRect(ctx,c.width,c.height,p.sqr.cr,true,false);ctx.translate(~~(c.width*0.5),~~(c.height*0.5));ctx.fillStyle="rgba("+p.bar.bgc+")";ctx.strokeStyle=p.bar.bc;ctx.lineWidth=p.bar.bw;var tx=p.r;var ty=-(p.bar.h+2*p.bar.bw)/2;var curBar=~~(progress*p.nb);var extraProgress=progress-(curBar/p.nb);for(var i=0;i<p.nbd;i++){ctx.save();var iBar=(curBar+i)%p.nb;var angle=iBar*2*Math.PI/p.nb;ctx.globalAlpha=(1/p.nb-extraProgress)+i*(1/p.nbd);ctx.rotate(angle);ctx.translate(tx,ty);mz.CanvasUtils.drawRoundRect(ctx,p.bar.w,p.bar.h,p.bar.cr,true,p.bar.bw>0);ctx.restore();}
this._currentTime=new Date().getTime();window.requestAnimationFrame(this._boundUpdate);}};p.destroy=function(){this.hide();this._canvasElt=null;this.divElt=null;};p.show=function(){if(!this._displayed&&this._canvasElt){this._rootDivElt.appendChild(this.divElt);this._displayed=true;this._update();}};p.hide=function(){if(this._displayed&&this._canvasElt){this._rootDivElt.removeChild(this.divElt);this._displayed=false;}};}
if(!mz.SoundManager){mz.SoundManager=function(player,lib,onReady){if(mz.log)console.log("Sound Manager",player,lib,onReady);this.onVolumeChange=new mz.Signal();this.onSoundChange=new mz.Signal();this._player=player;this._lib=lib;this._soundMap={};this._onReady=onReady;this._globalVolume=100;this._storedVolume=0;this._path=this._player._publishPath+"/mzMini/html5/mediaElement/";if(!window.mejs){mz.Launcher.loadScript(this._path+"mediaelement.min.js",this,this.onMediaElementLoaded)}else{this.onMediaElementLoaded();}}
var p=mz.SoundManager.prototype;p.onMediaElementLoaded=function(){if(mz.log)console.log("MediaElement loaded");this._soundCount=1;for(var soundId in this._lib){var src=this._player._publishPath+"/"+this._lib[soundId];if(src){this._soundCount++;this.buildSound(soundId,src);}}
this.soundLoaded();};p.soundLoaded=function(){if(mz.log)console.log("sound loaded",this._soundCount);this._soundCount--;if(this._soundCount==0){this._onReady();}};p.buildSound=function(id,soundSrc){if(mz.log)console.log("buildSound",id,soundSrc);if(typeof soundSrc=="string"){soundSrc=[soundSrc];}
if(soundSrc&&soundSrc.length>0){var html="<audio preload='preload' ";html+=">";for(var i=0;i<soundSrc.length;i++){var src=soundSrc[i];var ext=src.slice(-3);if(ext=="mp3"||ext=="ogg"){html+="<source src='"+src+"' type='audio/"+ext+"' />";}}
html+="</audio>";var div=document.createElement("div");div.innerHTML=html;var audioTag=div.firstChild;this._player._doc.rootDivElt.appendChild(audioTag);var self=this;mejs.MediaElement(audioTag,{enablePluginDebug:false,plugins:['flash','silverlight'],pluginPath:this._path,success:function(me){self._soundMap[id]=me;me.setLoop=function(value){audioTag.loop=value;}
var playingCallBack=function(){if(!me.playing){if(mz.log)console.log("playingCallBack "+me.src+" "+me.playing+" => "+true);me.playing=true;self.onSoundChange.dispatch(id,me.playing,me);}};var pausedCallBack=function(){if(me.playing){if(mz.log)console.log("pausedCallBack "+me.src+" "+me.playing+" => "+false);me.playing=false;self.onSoundChange.dispatch(id,me.playing,me);}};me.addEventListener("play",playingCallBack);me.addEventListener("playing",playingCallBack);me.addEventListener("pause",pausedCallBack);me.addEventListener("ended",pausedCallBack);me.addEventListener("canplay",function(){if(mz.log)console.log("canplay callback "+me.src+" playing:"+me.playing);me.canPlay=true;});self.soundLoaded();},error:function(){console.log("ME - ERROR",arguments);}});}};p.setMute=function(value){if(this.getMute()!=value){if(value){this._storedVolume=this.getGlobalVolume();this.setGlobalVolume(0);}else{if(this._storedVolume==0){this._storedVolume=50;}
this.setGlobalVolume(this._storedVolume);}}};p.getMute=function(){return this.getGlobalVolume()==0;};p.setGlobalVolume=function(value){if(this._globalVolume!=value){this._globalVolume=value;for(soundId in this._soundMap){sound=this._soundMap[soundId];this.updateSoundVolume(sound);}
this.onVolumeChange.dispatch(this._globalVolume);}};p.getGlobalVolume=function(){return this._globalVolume;}
p.executeAction=function(action){if(action&&action.type=="sound"){var operation=action.operation;if(mz.log)console.log("SoundManager.executeAction: "+operation);var sound,soundId;if(operation=="stopAll"){this.stopAllSounds();}else if(operation=="muteAll"||operation=="unmuteAll"){var newMute=operation=="muteAll";this.setMute(newMute);}else{soundId=action.soundId;sound=this._soundMap[soundId];if(sound){if(operation=="togglePlay"){if(sound.playing){operation="pause";}else{if(sound.paused){operation="resume";}else{operation="play";}}}
switch(operation){case"pause":sound.pause();break;case"resume":case"play":if(action.hasOwnProperty("volume")){sound._privateVolume=action.volume;}
if(action.hasOwnProperty("loop")){sound.setLoop(action.loop);}
this.updateSoundVolume(sound);if(operation=="play"){if(sound.canPlay){try{if(sound.pluginType!="flash"){sound.setCurrentTime(0);sound.play();}else{if(!sound.currentTime){sound.play();}else{sound.setCurrentTime(0);}}}catch(e){console.log("Play sound, setCurrentTime error "+e+"");}}else{sound.play();}}else{sound.play();}
break;}}}}};p.stopAllSounds=function(){for(var soundId in this._soundMap){var sound=this._soundMap[soundId];if(sound){try{sound.pause();}catch(e){console.log("stopAllSounds error:"+e,e);}}}};p.updateSoundVolume=function(sound){if(sound.hasOwnProperty("_privateVolume")){sound.setVolume(sound._privateVolume*0.01*this.getGlobalVolume()*0.01)}};p.isSoundPlaying=function(soundId){var sound=this._soundMap[soundId];return(sound&&sound.playing);};}
if(!mz.HTML5Player){mz.HTML5Player=function(doc,window,publishPath,timeStamp){var t=this;t._doc=null;t._scenes=null;t._animationStarted=false;t._loopCount=0;t._timeFactor=1;t._finished=false;t._sceneLoader=null;t._assetLoadCount=0;t._publishPath=null;t._timeStamp=null;t._engine=null;t._renderer=null;t._win=null;t._doc=null;t._boundRendererSlideTransitionUpdate=null;t._boundSlideTransitionEnd=null;t._boundRendererUpdate=null;t._boundStateEnd=null;t._shouldPause=false;t._paused=false;t._resumeFunction=null;if(mz.log)console.log("mz.Player","CONSTRUCTOR: ",doc.mzId,doc);if(!doc)throw new Error("no document found !");t._doc=doc;if(!doc.mzId)doc.mzId="mzDiv";if(doc.timeFactor)t._timeFactor=doc.timeFactor;t._scenes=doc.scenes;t._allSlides=[];t._win=window;t._dom=window.document;t._publishPath=publishPath;t._timeStamp=timeStamp;t._renderer=new mz.DOMRenderer(t._doc,t._win,t);t._engine=new mz.TransitionEngine(t._timeFactor);if(doc.hasEffect){t._effect=new mz.Effect();t._effect.init(t._doc,t._dom,t);}
t._boundRendererSlideTransitionUpdate=mz.bindFunction(t._renderer,t._renderer.slideTransitionUpdate);t._boundSlideTransitionEnd=mz.bindFunction(t,t._slideTransitionEnd);t._boundRendererUpdate=mz.bindFunction(t._renderer,t._renderer.update);t._boundStateEnd=mz.bindFunction(t,t.onStateEnd);};var p=mz.HTML5Player.prototype;p.init=function(){if(mz.log)console.log("mz.Player","onDOMReady",this._doc.id);var rootDiv=this._dom.getElementById(this._doc.mzId);rootDiv.innerHTML="";this._doc.rootDivElt=rootDiv;this._renderer.initRootDiv(rootDiv);if(this._doc.preloader){this._preloader=new mz.Preloader(this._doc,this._win);this._preloader.displayInRootDiv(rootDiv);}
this._assetLoadCount=1;this._preprocessAndLoadImages();if(this._doc.soundLib&&mz.SoundManager){var self=this;this._assetLoadCount++;this._soundManager=new mz.SoundManager(this,this._doc.soundLib,function(){self.decrLoadCount();});}
this._renderer.prepareAnimation();mz._triggerPlayerEvent(this._doc.mzId,"created");this.decrLoadCount();};p.decrLoadCount=function(){this._assetLoadCount--;if(this._assetLoadCount==0){this._onLoadingComplete();}};p._preprocessAndLoadImages=function(){if(mz.log)console.log("mz.Player","loadImages");var componentId,component,cloneComponent,slide;this._imageMap={};var self=this;var buildImageCallback=function(imgElt,success){return function(){self._onImageLoaded.apply(self,[imgElt,success]);}};this._totalDuration=0;for(var iScene=0,lenScene=this._scenes.length;iScene<lenScene;iScene++){var scene=this._scenes[iScene];var slides=scene.slides;for(var i=0,len=slides.length;i<len;i++){slide=slides[i];this.extendForTransitionEngine(slide);this._allSlides.push(slide);if(slide.transition){this._totalDuration+=slide.transition.duration;}
for(componentId in slide.components){component=slide.components[componentId];component.slide=slide;this.extendForTransitionEngine(component);var imgSrc=component.settings.src;if(component.type=="ImageComponent"&&imgSrc){if(this._doc.preloadAllScenes){if(!this._imageMap[imgSrc]){this._assetLoadCount++;var imgElt=this._dom.createElement("img");imgElt.onload=buildImageCallback(imgElt,true);imgElt.onerror=buildImageCallback(imgElt,false);imgSrc=this._buildImagePath(imgSrc);this._imageMap[component.settings.src]=imgSrc;component.settings.src=imgSrc;component.imgSrc=imgSrc;imgElt.src=imgSrc;}else{component.settings.src=this._imageMap[imgSrc];}}else{component.settings.src=null;component.imgSrc=this._buildImagePath(imgSrc);}}
if(component.settings.m=="rel"){component.hasMask=true;}
if(component.settings.oc){component.hasAction=true;}}
for(var j=0,len2=slide.states.length;j<len2;j++){var state=slide.states[j];this._totalDuration+=state.duration;for(componentId in state.transitions){component=slide.components[componentId];var transitionMap=state.transitions[componentId];for(var property in transitionMap){var transition=transitionMap[property];transition.property=property;transition.target=component;if(!transition.de)transition.de=0;if(transition.property=="m"){component.hasMask=true;}
if(transition.property=="oc"){component.hasAction=true;}}}}}}
if(this._doc.hasEffect){this._effect.preprocessDocument();}};p._buildImagePath=function(imgSrc){if(this._publishPath)imgSrc=this._publishPath+"/"+imgSrc;if(this._timeStamp)imgSrc=imgSrc+"#"+this._timeStamp;return imgSrc;};p.defaultValues={r:0,sx:1,sy:1,a:1,x:0,y:0,v:1};p._componentExtension={setValue:function(prop,value){return this.properties[prop]=value;},getValue:function(prop){return this.properties[prop];},setInitialValues:function(){for(var prop in this.settings){this.setValue(prop,this.settings[prop]);}
if(this.update)this.update(true);}};p.extendForTransitionEngine=function(o){if(!o.settings)o.settings={};o.properties={};for(var functionName in this._componentExtension){o[functionName]=this._componentExtension[functionName];}
for(var property in this.defaultValues){if(!o.settings.hasOwnProperty(property)){o.settings[property]=this.defaultValues[property];}}};p._onImageLoaded=function(imgElt,success){imgElt.onload=null;imgElt.onerror=null;this.decrLoadCount();};p._onLoadingComplete=function(){if(mz.log)console.log("mz.Player","onLoadingComplete","DOCUMENT:",this._doc);if(this._doc.preloader){if(this._doc.preloadAllScenes){this._preloader.destroy();delete this._preloader;delete this._doc.preloader;}else{this.extendForTransitionEngine(this._preloader);this._preloader.update=mz.DOMRenderer.slideUpdateFunction;}}
this._animationStarted=true;this.startAnimation();mz._triggerPlayerEvent(this._doc.mzId,"started");};p.publicActionCall=function(action){if(this._animationStarted&&!this._slideTransition){this.executeAction(action);}};p.startAnimation=function(){this.pos=new mz.PlayerPosition(this._doc);this.jumpToPos(false);};p.jumpToPos=function(shouldPlaySlideTransition){this.stopAll(true);if(this._preloader){this._preloader.hide();}
this._slideTransition=null;this._sceneChanged=false;this._slideChanged=false;if(mz.log)console.log(" ##############################");if(mz.log)console.log(" #SlideZestPlayer2 - jumpToPos:",this.pos.sceneIndex,this.pos.slideIndex,this.pos.stateIndex);if(this.pos.prevSceneIndex!=this.pos.sceneIndex){this._sceneChanged=true;this._slideChanged=true;}else{if(this.pos.prevSlideIndex!=this.pos.slideIndex){this._slideChanged=true;}}
var slideTransition=null;if(this.pos.prevSlideIndex>=0&&this.pos.prevSceneIndex>=0){var prevSlide=this.pos.scenes[this.pos.prevSceneIndex].slides[this.pos.prevSlideIndex];slideTransition=prevSlide.transition;if(this._slideChanged){this._renderer.hideSlide(prevSlide);}}
this._sceneLoaded=true;if(this._sceneChanged){this.pos.prevSceneIndex=this.pos.sceneIndex;if(!this._doc.preloadAllScenes){this._sceneLoaded=false;}}
if(slideTransition&&shouldPlaySlideTransition){this._slideTransition=slideTransition;this.playSlideTransition(prevSlide);}else{if(this._sceneChanged&&!this._doc.preloadAllScenes){this.preloadScene();}else{this.jumpToState();}}};p.preloadScene=function(){if(this._preloader){this._preloader.show();}
if(mz.log)console.log(" #SlideZestPlayer2 - preloadScene:",this.pos.sceneIndex,"time:",this.getTimer());if(!this._sceneLoader){this._sceneLoader=new mz.SceneLoader(this);}
this._sceneLoader.loadScene(this.pos.scene);};p.onSceneReady=function(){this._sceneLoaded=true;if(mz.log)console.log(" #SlideZestPlayer2 - onSceneReady:",this.pos.sceneIndex,"time:",this.getTimer());if(this._slideTransition){this.displayState();this.playSlideTransition();}else{if(this._preloader){this._preloader.hide();}
this.jumpToState();}};p.jumpToState=function(){if(mz.log)console.log(" #SlideZestPlayer2 - jumpToState:",this.pos.sceneIndex,this.pos.slideIndex,this.pos.stateIndex);this.displayState();this.playState();};p.displayState=function(){if(mz.log)console.log(" #SlideZestPlayer2 - displayState:",this.pos.sceneIndex,this.pos.slideIndex,this.pos.stateIndex);var fromState;var toState=this.pos.stateIndex;if(!this._slideChanged&&this.pos.prevStateIndex<this.pos.stateIndex){if(mz.log)console.log(" ---> going forward");fromState=this.pos.prevStateIndex;}else{if(mz.log)console.log(" ---> from slide start");this.layoutSlide();fromState=0;}
this.pos.goTo(this.pos.sceneIndex,this.pos.slideIndex,fromState);if(toState==0){this.playState(true);}else{for(var i=fromState;i<toState;i++){this.playState(true);this.pos.nextState();}}
if(mz.log)console.log(" ---> reached state",this.pos.stateIndex);};p.playSlideTransition=function(prevSlide){if(mz.log)console.log(" #SlideZestPlayer2 - playSlideTransition");var outElement;var inElement;if(this._sceneChanged&&!this._doc.preloadAllScenes){if(this._preloader){this._preloader.show();}
if(!this._sceneLoaded){if(mz.log)console.log("    -> scene out");outElement=prevSlide;inElement=this._preloader;inElement=this._preloader;}else{if(mz.log)console.log("    -> scene in",this.getTimer());outElement=this._preloader;inElement=this.pos.slide;}}else{this._slideTransitionSnapShot=this._renderer.takeSlideSnapShot(prevSlide);this.extendForTransitionEngine(this._slideTransitionSnapShot);this._slideTransitionSnapShot.setInitialValues();outElement=this._slideTransitionSnapShot;this.displayState();inElement=this.pos.slide;}
var transition=this._slideTransition;transition.inTransition.target=inElement;transition.outTransition.target=outElement;this._renderer.prepareForSlideTransition(inElement,outElement);if(inElement){inElement.setInitialValues();inElement.setValue(transition.inTransition.property,transition.inTransition.sv);inElement.update();this._engine.addTransition(transition.inTransition);}
if(outElement){outElement.setInitialValues();outElement.setValue(transition.outTransition.property,transition.outTransition.sv);outElement.update();this._engine.addTransition(transition.outTransition);}
this._engine.play(transition.duration,this._boundRendererSlideTransitionUpdate,this._boundSlideTransitionEnd);};p._slideTransitionEnd=function(){if(mz.log)console.log(" #SlideZestPlayer2 - slideTransitionEnd");if(this._slideTransition.outTransition.target){this._renderer.hideSlide(this._slideTransition.outTransition.target);}
if(this._sceneChanged&&!this._doc.preloadAllScenes){if(!this._sceneLoaded){this.preloadScene();}else{if(this._preloader){this._preloader.hide();}
this._slideTransition=null;this.playState();}}else{this.cleanSlideTransition();this.playState();}};p.cleanSlideTransition=function(){this._slideTransition=null;if(this._slideTransitionSnapShot){this._renderer.disposeSlideSnapShot(this._slideTransitionSnapShot);this._slideTransitionSnapShot=null;}};p.layoutSlide=function(){if(mz.log)console.log(" #SlideZestPlayer2 - layoutSlide:",this.pos.slideIndex);this.pos.prevSlideIndex=this.pos.slideIndex;this._initSlide(this.pos.slide);this._renderer.showSlide(this.pos.slide);};p._initSlide=function(slide){slide.setInitialValues();for(var componentId in slide.components){var component=slide.components[componentId];for(var prop in component.properties){delete component.properties[prop];}
component.setInitialValues();component.setValue("_parent",null);component.setValue("_effect",null);if(component.effects){for(var i=0;i<component.effects.length;i++){var effect=component.effects[i];for(var j=0;j<effect.elts.length;j++){effect.elts[j].setInitialValues();}}}}
this._renderer.initSlide(slide);};p.playState=function(skip){if(this._shouldPause&&!skip){this.doPause(this.playState);return;}
_paused=false;if(mz.log)console.log(" #SlideZestPlayer2 - playState",this.pos.stateIndex,"skip:",skip,"  (",this.getTimer(),")");this.pos.prevStateIndex=this.pos.stateIndex;if(this.pos.stateIndex==0&&this.pos.slide.onStart&&!skip){if(this.executeAction(this.pos.slide.onStart,true))return;}
if(this.pos.state.onStart&&!skip){if(this.executeAction(this.pos.state.onStart,true))return;}
this._handleGrouping(false);if(this.pos.stateIndex!==0){for(var componentId in this.pos.state.transitions){var component=this.pos.slide.components[componentId];var effectData=null;if(this.pos.state.effects){effectData=this.effectData.effects[component.id];}
if(effectData&&!skip){if(mz.log)console.log("effect.play",componentId);this._effect.play(effectData,this.pos.state);}
var transitionMap=this.pos.state.transitions[componentId];for(var property in transitionMap){var transition=transitionMap[property];if(transition.v!==component.properties[property]){if(!skip){if(!transition.effect){this._engine.addTransition(transition);}else{for(var i=0,len=transition.effect.transitions.length;i<len;i++){this._engine.addTransition(transition.effect.transitions[i]);}}}else{this._engine.applyTransition(transition);}}}}}
this._renderer.initState(this.pos.state,this.pos.slide);if(skip||this._totalDuration==0||this.pos.stateIndex==0){this._handleGrouping(true);}
if(!skip&&this._totalDuration!=0){if(this.pos.state.duration==0){this.onStateEnd();}else{this._engine.play(this.pos.state.duration,this._boundRendererUpdate,this._boundStateEnd);}}};p.onStateEnd=function(){this._handleGrouping(true);if(this.pos.state.onEnd){if(this.executeAction(this.pos.state.onEnd,true))return;}
if(this._shouldPause){this.doPause(this.doStateEnd);}else{this.doStateEnd();}};p._handleGrouping=function(group){var groups;if(group){groups=this.pos.state.startingGroups;}else{groups=this.pos.state.endingGroups;}
if(groups){if(mz.log)console.log("mz.Player","handleGrouping - group:"+group+" state: ",this.pos.state);for(var iGroup=0,lenGroups=groups.length;iGroup<lenGroups;iGroup++){var g=this.pos.slide.components[groups[iGroup]];if(mz.log)console.log("mz.Player","group",g);for(var iComponent=0,lenComponents=g.components.length;iComponent<lenComponents;iComponent++){var comonentId=g.components[iComponent];var component=this.pos.slide.components[comonentId];var values;if(group){values=g.startValues[comonentId];component.setValue("_parent",g);}else{values=g.endValues[comonentId];component.setValue("_parent",null);}
for(var property in values){component.setValue(property,values[property]);}
if(component.update){component.update();}}}}};p.doStateEnd=function(){if(this.pos.stateIndex+1>=this.pos.states.length){if(this.pos.slide.onEnd){if(this.executeAction(this.pos.slide.onEnd,true))return;}
if(this._shouldPause){this.doPause(this.slideEnd);}else{this.slideEnd();}}else{this.pos.nextState();this.playState();}};p.slideEnd=function(){this.pos.nextSlide();this.jumpToPos(true);};p.play=function(){if(this._paused){this.doResume();}};p.doPause=function(playFunction){this._paused=true;this._shouldPause=false;this._playFunction=playFunction;if(!this._engine.isPaused()&&this._engine.isStarted()){this._engine.pause();}};p.doResume=function(){this._paused=false;if(this._engine.isPaused()){this._engine.resume();}
if(this._playFunction!=null){this._playFunction();}};p.pause=function(){this._shouldPause=true;if(!this._inCodeExecution){this.doPause();}};p.togglePlayPause=function(){if(this._paused){this.play();}else{this.pause();}};p.stopAll=function(){if(this._engine.isStarted()){this._engine.stop();}};p.onNextFrame=function(){this._jumpedOnThatFrame=false;};p.nextState=function(){this.pos.nextState();this.jumpToPos(false);};p.prevState=function(){this.pos.prevState();this.jumpToPos(false);};p.nextSlide=function(playSlideTransition){this.pos.nextSlide();this.jumpToPos(playSlideTransition);};p.prevSlide=function(playSlideTransition){this.pos.prevSlide();this.jumpToPos(playSlideTransition);};p.nextScene=function(playSlideTransition){this.pos.nextScene();this.jumpToPos(playSlideTransition);};p.prevScene=function(playSlideTransition){this.pos.prevScene();this.jumpToPos(playSlideTransition);};p.goTo=function(sceneIndex,slideIndex,stateIndex,playSlideTransition){this.pos.goTo(sceneIndex,slideIndex,stateIndex);this.jumpToPos(playSlideTransition);};p.executeAction=function(a,inCodeExecution){if(this._slideTransition||!this._sceneLoaded){return false;}
this._inCodeExecution=inCodeExecution;var hasJump=false;if(typeof a=="object"){if(a.length){for(var i=0,len=a.length;i<len;i++){hasJump=this.executeMonoAction(a[i])||hasJump;}}else if(a.type){hasJump=this.executeMonoAction(a);}}
this._inCodeExecution=false;return hasJump;};var PLAYER_JUMP_TYPES_ARRAY=["goTo","nextScene","prevScene","nextSlide","prevSlide","nextState","prevState"];p.executeMonoAction=function(a){if(mz.log)console.log("Do Action",a.type,a,this);var isJumpAction=PLAYER_JUMP_TYPES_ARRAY.indexOf(a.type)>=0;if(isJumpAction){if(!this._jumpedOnThatFrame){var doSlideAnim=a.playSlideTransition;switch(a.type){case"goTo":if(a.pause){this._shouldPause=true;}
this.goTo(a.sceneIndex,a.slideIndex,a.stateIndex,doSlideAnim);break;case"nextScene":this.nextScene(doSlideAnim);break;case"prevScene":this.prevScene(doSlideAnim);break;case"nextSlide":this.nextSlide(doSlideAnim);break;case"prevSlide":this.prevSlide(doSlideAnim);break;case"nextState":this.nextState();break;case"prevState":this.prevState();break;}}}else{switch(a.type){case"playPause":this.togglePlayPause();break;case"pause":this.pause();break;case"play":this.play();break;case"executeJS":var functionName=a.functionName||a.arg1;var args=a.arguments||a.arg2;var f=this._win[functionName];if(f){f(args);}else{console.log("function does not exist: "+a.functionName);}
break;case"openUrl":var url=a.url||a.arg1;var urlTarget=a.urlTarget||a.arg2;if(mz.log)console.log("mz.Player","openUrl",url,urlTarget);if(urlTarget=="_blank"){this._win.open(url);}else{this._win.open(url,urlTarget);}
break;case"digitalPublishingAction":var f=this._win["mcOutAction"];var actionId=a.actionId||a.arg1;if(f){console.log("DigitalPublishing=> calling mcOutAction("+actionId+")");f(actionId);}else{console.log("function does not exist: mcOutAction");}
break;case"sound":if(this._soundManager){this._soundManager.executeAction(a);}
break;}}
return isJumpAction&&!this._jumpedOnThatFrame;};p.getTimer=function(){if(!p._startTime)p._startTime=Date.now();return Date.now()-p._startTime;};}
if(!mz.PlayerPosition){mz.PlayerPosition=function(document,sceneIndex,slideIndex,stateIndex){this.prevStateIndex=-1;this.prevSlideIndex=-1;this.prevSceneIndex=-1;this.stateIndex=-1;this.slideIndex=-1;this.sceneIndex=-1;this.states=null;this.slides=null;this.scenes=null;this.scene=null;this.slide=null;this.state=null;this.document=document;this.scenes=document.scenes;this.goTo(sceneIndex||0,slideIndex||0,sceneIndex||0);};mz.PlayerPosition.prototype.goTo=function(sceneIndex,slideIndex,stateIndex){if(sceneIndex<0){sceneIndex=0;}else if(sceneIndex>=this.scenes.length){sceneIndex=this.scenes.length-1;}
this.sceneIndex=sceneIndex;this.scene=this.scenes[sceneIndex];this.slides=this.scene.slides;if(slideIndex<0){slideIndex=0;}else if(slideIndex>=this.slides.length){slideIndex=this.slides.length-1;}
this.slideIndex=slideIndex;this.slide=this.slides[slideIndex];this.states=this.slide.states;if(stateIndex<0){stateIndex=0;}else if(stateIndex>=this.states.length){stateIndex=this.states.length-1;}
this.stateIndex=stateIndex;this.state=this.states[stateIndex];};mz.PlayerPosition.prototype.nextState=function(){if(this.stateIndex+1>=this.states.length){this.nextSlide();}else{this.goTo(this.sceneIndex,this.slideIndex,this.stateIndex+1);}};mz.PlayerPosition.prototype.prevState=function(){if(this.stateIndex-1<0){this.prevSlide(true);}else{this.goTo(this.sceneIndex,this.slideIndex,this.stateIndex-1);}};mz.PlayerPosition.prototype.nextSlide=function(){if(this.slideIndex+1>=this.slides.length){this.nextScene();}else{this.goTo(this.sceneIndex,this.slideIndex+1,0);}};mz.PlayerPosition.prototype.prevSlide=function(goToEnd){if(this.slideIndex-1<0){this.prevScene(true,goToEnd);}else{var si=0;if(goToEnd){si=this.slides[this.slideIndex-1].states.length-1;}
this.goTo(this.sceneIndex,this.slideIndex-1,si);}};mz.PlayerPosition.prototype.nextScene=function(){if(this.sceneIndex+1>=this.scenes.length){this.goTo(0,0,0);}else{this.goTo(this.sceneIndex+1,0,0);}};mz.PlayerPosition.prototype.prevScene=function(goToEnd,goToSlideEnd){var nextSceneIndex=0;var nextSlideIndex=0;var nextStateIndex=0;if(this.sceneIndex-1<0){nextSceneIndex=this.scenes.length-1;}else{nextSceneIndex=this.sceneIndex-1;}
if(goToEnd){nextSlideIndex=this.scenes[nextSceneIndex].slides.length-1;}
if(goToSlideEnd){nextStateIndex=this.scenes[nextSceneIndex].slides[nextStateIndex].states.length-1;}
this.goTo(nextSceneIndex,nextSlideIndex,nextStateIndex);};}
if(!mz.SceneLoader){mz.SceneLoader=function(player){this._player=player;this._scene=null;this._imageMap=null;this._loadCount=null;var self=this;this.onImageLoadedBound=function(){self.onImageLoaded();};};mz.SceneLoader.prototype.loadScene=function(scene){var i,compId,slide,component;if(scene!=this._scene){if(this._scene){for(i=0;i<this._scene.slides.length;i++){slide=this._scene.slides[i];for(j=0;j<slide.components.length;j++){component=slide.components[j];if(component.type=="ImageComponent"&&component.imgSrc){component.settings.src=null;component.update();}}}}
this._scene=scene;this._imageMap={};this._loadCount=1;for(i=0;i<this._scene.slides.length;i++){slide=this._scene.slides[i];for(compId in slide.components){component=slide.components[compId];if(component.type=="ImageComponent"&&component.imgSrc){component.settings.src=component.imgSrc;component.update();if(!this._imageMap[component.imgSrc]){var image=new Image();image.src=component.imgSrc;var loaded=false;if(image.complete){loaded=true;}else if(typeof image.naturalWidth!="undefined"&&image.naturalWidth!==0){loaded=true;}
if(loaded){this._imageMap[component.imgSrc]=true;}else{this._imageMap[component.imgSrc]=image;this._loadCount++;image.onload=this.onImageLoadedBound;image.onerror=this.onImageLoadedBound;image.style.position="absolute";image.style.left=10*this._loadCount+"px";image.style.top="0px";}}}}}
this.onImageLoaded();}else{this._player.onSceneReady();}};mz.SceneLoader.prototype.onImageLoaded=function(){this._loadCount--;if(this._loadCount==0){try{this._player.onSceneReady();}catch(e){throw new Error();}}}}
if(mz.log)console.log("mzLib created");})();
